name = "SwiftMobile"
author = "Zen"
version = "8.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76d88370f2becb378b3191e73a4f8e03f0ac907378706b6ef792807c2ddd6585"

[versions]
fabric = "0.19.3"
minecraft = "1.21.4"
