name = "SwiftMobile"
author = "Zen"
version = "12.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d96a4cfccd3a0094881c012e9050be950ed08d2c45b167bb449bab5124519260"

[versions]
fabric = "0.19.3"
icon = "pack.png"
minecraft = "1.21.11"
