name = "SwiftMobile"
author = "Zen"
version = "12.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06d9b571c9e54586237fac266b9acd419b88a39f6c661be8e1553c7a7f30bb94"

[versions]
fabric = "0.19.3"
icon = "pack.png"
minecraft = "1.21.11"
