name = "SwiftMobile"
author = "Zen"
version = "5.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ad66582cce665ddc6ba0b7e6809240b54e5fa69126bc9bb3a27eba31948dce0"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
